/* Service worker for gamutlens.com.
 * GENERATED by tools/build_color_pages.mjs. Do not edit by hand.
 * VERSION is a hash of every precached file. A new deploy gets a new cache
 * name, and activate() deletes the old cache. */
const VERSION = "4ef26e5dec98"
const CACHE = "gamutlens-" + VERSION
const PRECACHE = [
  "/",
  "/color-picker/",
  "/color-converter/",
  "/gradient-generator/",
  "/color-palette-generator/",
  "/contrast-checker/",
  "/image-color-extractor/",
  "/color-shades-generator/",
  "/color-name-finder/",
  "/color-blindness-simulator/",
  "/hex-to-oklch/",
  "/rgb-to-cmyk/",
  "/oklch-to-hex/",
  "/shades-of-blue/",
  "/shades-of-green/",
  "/shades-of-pink/",
  "/shades-of-purple/",
  "/shades-of-red/",
  "/shades-of-orange/",
  "/shades-of-yellow/",
  "/shades-of-brown/",
  "/shades-of-grey/",
  "/shades-of-teal/",
  "/privacy/",
  "/terms/",
  "/articles/",
  "/articles/hex-rgb-hsl-which-color-format-to-use/",
  "/articles/how-wcag-contrast-ratios-work/",
  "/articles/color-harmony-complementary-analogous-triadic/",
  "/articles/why-gradients-go-grey-in-the-middle/",
  "/assets/app.js",
  "/assets/color-math.js",
  "/assets/color-names.js",
  "/assets/style.css",
]

self.addEventListener("install", event => {
  // cache: "reload" makes each fetch skip the HTTP cache, so the precache
  // never receives stale bytes from an earlier visit.
  event.waitUntil(
    caches.open(CACHE)
      .then(cache => cache.addAll(PRECACHE.map(url => new Request(url, { cache: "reload" }))))
      .then(() => self.skipWaiting())
  )
})

self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(key => key.startsWith("gamutlens-") && key !== CACHE).map(key => caches.delete(key))
      ))
      .then(() => self.clients.claim())
  )
})

self.addEventListener("fetch", event => {
  const request = event.request
  // Only a same-origin GET request gets a cached answer. Every other request
  // returns here without respondWith(). That includes the AdSense script and
  // every other third-party request: the worker never intercepts them and
  // never caches them.
  if (request.method !== "GET") return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  // Cache first. The precache is the whole offline set, so a network response
  // is never written into the cache at runtime.
  event.respondWith(
    caches.match(request, { ignoreSearch: false }).then(hit => {
      if (hit) return hit
      if (request.mode !== "navigate") return fetch(request)
      // A navigation with a query string, or to a file inside a directory,
      // falls back to the precached page for that path.
      return caches.match(url.pathname)
        .then(byPath => byPath || (url.pathname.endsWith("/") ? caches.match(url.pathname + "index.html") : undefined))
        .then(cached => cached || fetch(request))
    })
  )
})
